// =============================================================================
// data.js
// Test fixture data mirroring migrations/psql/seed.sql.
// Each entry matches the CreatePnmBody shape: { info, on_campus, off_campus, interests }
// =============================================================================

export const interests = [
    'Engineering',
    'Music',
    'Gaming',
    'Basketball',
    'Soccer',
    'Film',
    'Cooking',
    'Photography',
    'Hiking',
    'Finance',
];

export const PNMS = [
    {
        info: {
            first_name: 'James',
            last_name: 'Carter',
            class_year: 'FRESHMAN',
            status_type: 'DELTA',
            email: 'james.carter@uni.edu',
            phone_number: '555-101-0001',
        },
        on_campus: { dorm: 'SPEED', room_number: '101' },
        off_campus: null,
        interests: ['Engineering', 'Gaming'],
    },
    {
        info: {
            first_name: 'Maria',
            last_name: 'Lopez',
            class_year: 'SOPHOMORE',
            status_type: 'SIGMA',
            email: 'maria.lopez@uni.edu',
            phone_number: '555-101-0002',
        },
        on_campus: { dorm: 'BSB', room_number: '204' },
        off_campus: null,
        interests: ['Music', 'Photography'],
    },
    {
        info: {
            first_name: 'Tyler',
            last_name: 'Brooks',
            class_year: 'JUNIOR',
            status_type: 'PHI',
            email: 'tyler.brooks@uni.edu',
            phone_number: '555-101-0003',
        },
        on_campus: { dorm: 'BLUMBERG', room_number: '312' },
        off_campus: null,
        interests: ['Basketball', 'Film'],
    },
    {
        info: {
            first_name: 'Aisha',
            last_name: 'Patel',
            class_year: 'SENIOR',
            status_type: 'DELTA',
            email: 'aisha.patel@uni.edu',
            phone_number: '555-101-0004',
        },
        on_campus: null,
        off_campus: {
            street_address: '742 Evergreen Terrace',
            city: 'Springfield',
            state: 'IL',
            zip_code: '62701',
        },
        interests: ['Finance', 'Cooking'],
    },
    {
        info: {
            first_name: 'Connor',
            last_name: 'Wu',
            class_year: 'SUPER_SENIOR',
            status_type: 'SIGMA',
            email: 'connor.wu@uni.edu',
            phone_number: '555-101-0005',
        },
        on_campus: null,
        off_campus: {
            street_address: '1600 Maple Ave Apt 3',
            city: 'Shelbyville',
            state: 'IL',
            zip_code: '62565',
        },
        interests: ['Soccer', 'Gaming', 'Film'],
    },
    {
        info: {
            first_name: 'Sophia',
            last_name: 'Nguyen',
            class_year: 'FRESHMAN',
            email: 'sophia.nguyen@uni.edu',
            phone_number: '555-101-0006',
        },
        on_campus: { dorm: 'LAKESIDE', room_number: '405' },
        off_campus: null,
        interests: ['Hiking', 'Photography'],
    },
    {
        info: {
            first_name: 'Marcus',
            last_name: 'Johnson',
            class_year: 'SOPHOMORE',
            status_type: 'PHI',
            email: 'marcus.johnson@uni.edu',
            phone_number: '555-101-0007',
        },
        on_campus: { dorm: 'MEES', room_number: '118' },
        off_campus: null,
        interests: ['Basketball', 'Engineering'],
    },
    {
        info: {
            first_name: 'Elena',
            last_name: 'Rivera',
            class_year: 'JUNIOR',
            status_type: 'DELTA',
            email: 'elena.rivera@uni.edu',
            phone_number: '555-101-0008',
        },
        on_campus: null,
        off_campus: {
            street_address: '221 Baker Street',
            city: 'Capital City',
            state: 'IL',
            zip_code: '62701',
        },
        interests: ['Music', 'Cooking', 'Hiking'],
    },
    {
        info: {
            first_name: 'Noah',
            last_name: 'Kim',
            class_year: 'SENIOR',
            email: 'noah.kim@uni.edu',
            phone_number: '555-101-0009',
        },
        on_campus: null,
        off_campus: {
            street_address: '55 Water Street Apt 9C',
            city: 'Springfield',
            state: 'IL',
            zip_code: '62704',
        },
        interests: ['Finance', 'Soccer'],
    },
    {
        info: {
            first_name: 'Priya',
            last_name: 'Sharma',
            class_year: 'FRESHMAN',
            status_type: 'SIGMA',
            email: 'priya.sharma@uni.edu',
            phone_number: '555-101-0010',
        },
        on_campus: { dorm: 'APARTMENTS EAST', room_number: '2B' },
        off_campus: null,
        interests: ['Engineering', 'Film', 'Gaming'],
    },
];

export const PNMS_FLAT = [
    {
        "first_name": "James",
        "last_name": "Carter",
        "class_year": "FRESHMAN",
        "status_type": "DELTA",
        "email": "james.carter@uni.edu",
        "phone_number": "555-101-0001",
        "dorm": "SPEED",
        "room_number": "101",
        "street_address": null,
        "city": null,
        "state": null,
        "zip_code": null,
        "interests": ["Engineering", "Gaming"]
    },
    {
        "first_name": "Maria",
        "last_name": "Lopez",
        "class_year": "SOPHOMORE",
        "status_type": "SIGMA",
        "email": "maria.lopez@uni.edu",
        "phone_number": "555-101-0002",
        "dorm": "BSB",
        "room_number": "204",
        "street_address": null,
        "city": null,
        "state": null,
        "zip_code": null,
        "interests": ["Music", "Photography"]
    },
    {
        "first_name": "Tyler",
        "last_name": "Brooks",
        "class_year": "JUNIOR",
        "status_type": "PHI",
        "email": "tyler.brooks@uni.edu",
        "phone_number": "555-101-0003",
        "dorm": "BLUMBERG",
        "room_number": "312",
        "street_address": null,
        "city": null,
        "state": null,
        "zip_code": null,
        "interests": ["Basketball", "Film"]
    },
    {
        "first_name": "Aisha",
        "last_name": "Patel",
        "class_year": "SENIOR",
        "status_type": "DELTA",
        "email": "aisha.patel@uni.edu",
        "phone_number": "555-101-0004",
        "dorm": null,
        "room_number": null,
        "street_address": "742 Evergreen Terrace",
        "city": "Springfield",
        "state": "IL",
        "zip_code": "62701",
        "interests": ["Finance", "Cooking"]
    },
    {
        "first_name": "Connor",
        "last_name": "Wu",
        "class_year": "SUPER_SENIOR",
        "status_type": "SIGMA",
        "email": "connor.wu@uni.edu",
        "phone_number": "555-101-0005",
        "dorm": null,
        "room_number": null,
        "street_address": "1600 Maple Ave Apt 3",
        "city": "Shelbyville",
        "state": "IL",
        "zip_code": "62565",
        "interests": ["Soccer", "Gaming", "Film"]
    },
    {
        "first_name": "Sophia",
        "last_name": "Nguyen",
        "class_year": "FRESHMAN",
        "status_type": null,
        "email": "sophia.nguyen@uni.edu",
        "phone_number": "555-101-0006",
        "dorm": "LAKESIDE",
        "room_number": "405",
        "street_address": null,
        "city": null,
        "state": null,
        "zip_code": null,
        "interests": ["Hiking", "Photography"]
    },
    {
        "first_name": "Marcus",
        "last_name": "Johnson",
        "class_year": "SOPHOMORE",
        "status_type": "PHI",
        "email": "marcus.johnson@uni.edu",
        "phone_number": "555-101-0007",
        "dorm": "MEES",
        "room_number": "118",
        "street_address": null,
        "city": null,
        "state": null,
        "zip_code": null,
        "interests": ["Basketball", "Engineering"]
    },
    {
        "first_name": "Elena",
        "last_name": "Rivera",
        "class_year": "JUNIOR",
        "status_type": "DELTA",
        "email": "elena.rivera@uni.edu",
        "phone_number": "555-101-0008",
        "dorm": null,
        "room_number": null,
        "street_address": "221 Baker Street",
        "city": "Capital City",
        "state": "IL",
        "zip_code": "62701",
        "interests": ["Music", "Cooking", "Hiking"]
    },
    {
        "first_name": "Noah",
        "last_name": "Kim",
        "class_year": "SENIOR",
        "status_type": null,
        "email": "noah.kim@uni.edu",
        "phone_number": "555-101-0009",
        "dorm": null,
        "room_number": null,
        "street_address": "55 Water Street Apt 9C",
        "city": "Springfield",
        "state": "IL",
        "zip_code": "62704",
        "interests": ["Finance", "Soccer"]
    },
    {
        "first_name": "Priya",
        "last_name": "Sharma",
        "class_year": "FRESHMAN",
        "status_type": "SIGMA",
        "email": "priya.sharma@uni.edu",
        "phone_number": "555-101-0010",
        "dorm": "APARTMENTS EAST",
        "room_number": "2B",
        "street_address": null,
        "city": null,
        "state": null,
        "zip_code": null,
        "interests": ["Engineering", "Film", "Gaming"]
    }
]
