/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PnmsRouteImport } from './routes/pnms'
import { Route as PnmsIndexRouteImport } from './routes/pnms/index'
import { Route as PnmsPnmIdRouteImport } from './routes/pnms/$pnmId'
import { Route as PnmsCreateRouteImport } from './routes/pnms/create'
import { Route as PnmsPnmIdIndexRouteImport } from './routes/pnms/$pnmId.index'
import { Route as PnmsPnmIdEditRouteImport } from './routes/pnms/$pnmId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PnmsRoute = PnmsRouteImport.update({
  id: '/pnms',
  path: '/pnms',
  getParentRoute: () => rootRouteImport,
} as any)
const PnmsIndexRoute = PnmsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PnmsRoute,
} as any)
const PnmsPnmIdRoute = PnmsPnmIdRouteImport.update({
  id: '/$pnmId',
  path: '/$pnmId',
  getParentRoute: () => PnmsRoute,
} as any)
const PnmsCreateRoute = PnmsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => PnmsRoute,
} as any)
const PnmsPnmIdIndexRoute = PnmsPnmIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PnmsPnmIdRoute,
} as any)
const PnmsPnmIdEditRoute = PnmsPnmIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PnmsPnmIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pnms': typeof PnmsRouteWithChildren
  '/pnms/$pnmId': typeof PnmsPnmIdRouteWithChildren
  '/pnms/create': typeof PnmsCreateRoute
  '/pnms/': typeof PnmsIndexRoute
  '/pnms/$pnmId/edit': typeof PnmsPnmIdEditRoute
  '/pnms/$pnmId/': typeof PnmsPnmIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pnms/create': typeof PnmsCreateRoute
  '/pnms': typeof PnmsIndexRoute
  '/pnms/$pnmId/edit': typeof PnmsPnmIdEditRoute
  '/pnms/$pnmId': typeof PnmsPnmIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pnms': typeof PnmsRouteWithChildren
  '/pnms/$pnmId': typeof PnmsPnmIdRouteWithChildren
  '/pnms/create': typeof PnmsCreateRoute
  '/pnms/': typeof PnmsIndexRoute
  '/pnms/$pnmId/edit': typeof PnmsPnmIdEditRoute
  '/pnms/$pnmId/': typeof PnmsPnmIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pnms'
    | '/pnms/$pnmId'
    | '/pnms/create'
    | '/pnms/'
    | '/pnms/$pnmId/edit'
    | '/pnms/$pnmId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pnms/create'
    | '/pnms'
    | '/pnms/$pnmId/edit'
    | '/pnms/$pnmId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/pnms'
    | '/pnms/$pnmId'
    | '/pnms/create'
    | '/pnms/'
    | '/pnms/$pnmId/edit'
    | '/pnms/$pnmId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PnmsRoute: typeof PnmsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pnms': {
      id: '/pnms'
      path: '/pnms'
      fullPath: '/pnms'
      preLoaderRoute: typeof PnmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pnms/': {
      id: '/pnms/'
      path: '/'
      fullPath: '/pnms/'
      preLoaderRoute: typeof PnmsIndexRouteImport
      parentRoute: typeof PnmsRoute
    }
    '/pnms/$pnmId': {
      id: '/pnms/$pnmId'
      path: '/$pnmId'
      fullPath: '/pnms/$pnmId'
      preLoaderRoute: typeof PnmsPnmIdRouteImport
      parentRoute: typeof PnmsRoute
    }
    '/pnms/create': {
      id: '/pnms/create'
      path: '/create'
      fullPath: '/pnms/create'
      preLoaderRoute: typeof PnmsCreateRouteImport
      parentRoute: typeof PnmsRoute
    }
    '/pnms/$pnmId/': {
      id: '/pnms/$pnmId/'
      path: '/'
      fullPath: '/pnms/$pnmId/'
      preLoaderRoute: typeof PnmsPnmIdIndexRouteImport
      parentRoute: typeof PnmsPnmIdRoute
    }
    '/pnms/$pnmId/edit': {
      id: '/pnms/$pnmId/edit'
      path: '/edit'
      fullPath: '/pnms/$pnmId/edit'
      preLoaderRoute: typeof PnmsPnmIdEditRouteImport
      parentRoute: typeof PnmsPnmIdRoute
    }
  }
}

interface PnmsPnmIdRouteChildren {
  PnmsPnmIdEditRoute: typeof PnmsPnmIdEditRoute
  PnmsPnmIdIndexRoute: typeof PnmsPnmIdIndexRoute
}

const PnmsPnmIdRouteChildren: PnmsPnmIdRouteChildren = {
  PnmsPnmIdEditRoute: PnmsPnmIdEditRoute,
  PnmsPnmIdIndexRoute: PnmsPnmIdIndexRoute,
}

const PnmsPnmIdRouteWithChildren = PnmsPnmIdRoute._addFileChildren(
  PnmsPnmIdRouteChildren,
)

interface PnmsRouteChildren {
  PnmsPnmIdRoute: typeof PnmsPnmIdRouteWithChildren
  PnmsCreateRoute: typeof PnmsCreateRoute
  PnmsIndexRoute: typeof PnmsIndexRoute
}

const PnmsRouteChildren: PnmsRouteChildren = {
  PnmsPnmIdRoute: PnmsPnmIdRouteWithChildren,
  PnmsCreateRoute: PnmsCreateRoute,
  PnmsIndexRoute: PnmsIndexRoute,
}

const PnmsRouteWithChildren = PnmsRoute._addFileChildren(PnmsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PnmsRoute: PnmsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
